---
title: "ANALISE WSCAD"
output:
  html_document:
    keep_md: yes
---

# BIBLIOTECAS
```{r}
library(ggplot2)
```

# DADOS

```{r}
metricas <- c(7, 16, 19, 23, 21, 26, 12, 12, 17, 16, 16, 5, 17, 16, 23, 11, 17, 15, 18, 22, 13, 11)

termos <- c(5, 20, 22, 28, 30, 31, 24, 17, 24, 14, 12, 5, 22, 17, 29, 12, 16, 9, 19, 22, 16, 12)

testes <- c(0, 1, 0, 0, 0, 0, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 0, 2, 3, 2, 0)

artigos <- c(9, 23, 27, 32, 33, 34, 28, 21, 28, 23, 20, 6, 28, 20, 39, 15, 21, 19, 19, 23, 16, 13)

citacao_metricas <- c(17, 29, 31, 38, 38, 36, 15, 17, 33, 23, 21, 8, 24, 31, 32, 17, 28, 22, 18, 23, 16, 13)

citacao_termos <- c(7, 34, 35, 40, 53, 58, 38, 28, 31, 18, 19, 8, 33, 31, 33, 16, 23, 13, 18, 23, 16, 13)

citacao_testes <- c(0, 1, 0, 0, 0, 0, 0, 4, 1, 1, 0, 0, 2, 0, 0, 1, 1, 0, 2, 2, 2, 0)

```

# PERCENTUAIS

```{r}
metricas_ano <- c()
termos_ano <- c()
testes_ano <- c()

cit_met_ano <- c()
cit_est_ano <- c()
cit_tst_ano <- c()

anos <- seq(2000, 2021, 1)

for (ano in 1:22){
  metricas_ano <- append(metricas_ano, metricas[ano]/artigos[ano]*100)
  termos_ano <- append(termos_ano, termos[ano]/artigos[ano]*100)
  testes_ano <- append(testes_ano, testes[ano]/artigos[ano]*100)
  
  cit_met_ano <- append(cit_met_ano, citacao_metricas[ano]/artigos[ano])
  cit_est_ano <- append(cit_est_ano, citacao_termos[ano]/artigos[ano])
  cit_tst_ano <- append(cit_tst_ano, citacao_testes[ano]/artigos[ano])
  
}
```

# DATAFRAMES

```{r}
df_dados <- data.frame(anos, artigos, metricas, termos, testes)

df_percent <- data.frame(anos, metricas_ano, termos_ano, testes_ano)

df_citacao <- data.frame(anos, cit_met_ano, cit_est_ano, cit_tst_ano)

```

# GRÁFICOS

```{r}
colors <- c("Métricas" = "red", "Termos" = "blue", "Testes" = "darkgreen")

ggplot(data=df_percent, aes(x=anos)) + 
  geom_line(aes(y = metricas_ano, color="Métricas"), size=1) +
  geom_line(aes(y = termos_ano, color="Termos"), size=1) +
  geom_line(aes(y = testes_ano, color="Testes"), size=1) +
  scale_x_continuous(breaks = anos, guide = guide_axis(angle = 90)) +
  scale_color_manual(values = colors) +
  labs(title = "Proporção de artigos com citação por ano", x = "", y = "% de artigos", color = "")
  

ggplot(data=df_citacao, aes(x=anos)) + 
  geom_line(aes(y = cit_met_ano, color="Métricas"), size=1) +
  geom_line(aes(y = cit_est_ano, color="Termos"), size=1) +
  geom_line(aes(y = cit_tst_ano, color="Testes"), size=1) +
  scale_x_continuous(breaks = anos, guide = guide_axis(angle = 90)) +
  scale_color_manual(values = colors) +
  labs(title = "Razão de citações de artigos por ano", x = "", y = "Razão de citações/artigos", color = "")
  
```

# ANOVA

```{r}
df_dados[1:19, 'situacao'] <- "velho"

df_dados[20:22, 'situacao'] <- "novo"

df_dados

alfa <- 5/100
k <- 2
n <- length(df_dados$situacao)


f_critico <- qf(1 - alfa, df1 = k - 1, df2 = n - k)

f_critico

aov_metricas <- aov(metricas ~ situacao, df_dados)
aov_testes <- aov(testes ~ situacao, df_dados)
aov_termos <- aov(termos ~ situacao, df_dados)

summary(aov_metricas)
summary(aov_testes)
summary(aov_termos)

``` 